// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type EventDocumentDataSlicesSlice = never;

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Content field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Start field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start: prismic.DateField;

  /**
   * End field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end: prismic.DateField;

  /**
   * Location field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

type EventsOverviewPageDocumentDataSlicesSlice = never;

/**
 * Content for Events Overview Page documents
 */
interface EventsOverviewPageDocumentData {
  /**
   * Title field in *Events Overview Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_overview_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Events Overview Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_overview_page.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Slice Zone field in *Events Overview Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: events_overview_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventsOverviewPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Events Overview Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: events_overview_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Events Overview Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: events_overview_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Events Overview Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events_overview_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Events Overview Page document from Prismic
 *
 * - **API ID**: `events_overview_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsOverviewPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventsOverviewPageDocumentData>,
    "events_overview_page",
    Lang
  >;

type GameDocumentDataSlicesSlice =
  | TeamInfoSlice
  | TextWithImageSlice
  | CustomerLogosSlice
  | LeistungenSlice
  | RichTextSlice
  | EventsSlice
  | TeamSlice;

/**
 * Content for Game documents
 */
interface GameDocumentData {
  /**
   * Game field in *Game*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game.game
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  game: prismic.KeyTextField;

  /**
   * Title field in *Game*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Game*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Header Image field in *Game*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: game.header_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Game*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: game.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GameDocumentDataSlicesSlice> /**
   * Meta Title field in *Game*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: game.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Game*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: game.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Game*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: game.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Game document from Prismic
 *
 * - **API ID**: `game`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GameDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<GameDocumentData>, "game", Lang>;

type HomepageDocumentDataSlicesSlice =
  | ContactFormSlice
  | HeroSlice
  | InfoGridSlice
  | RichTextSlice
  | GamesSlice
  | LeistungenSlice
  | CustomerLogosSlice
  | TextWithImageSlice
  | EventsSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type LeistungDocumentDataSlicesSlice =
  | InfoGridSlice
  | RichTextSlice
  | CustomerLogosSlice
  | EventsSlice
  | TextWithImageSlice;

/**
 * Content for Leistung documents
 */
interface LeistungDocumentData {
  /**
   * Index field in *Leistung*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: leistung.index
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  index: prismic.NumberField;

  /**
   * Title field in *Leistung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leistung.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Short Description field in *Leistung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leistung.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_description: prismic.KeyTextField;

  /**
   * Icon field in *Leistung*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leistung.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Image field in *Leistung*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leistung.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Leistung*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: leistung.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LeistungDocumentDataSlicesSlice> /**
   * Meta Title field in *Leistung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: leistung.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Leistung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: leistung.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Leistung*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leistung.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Leistung document from Prismic
 *
 * - **API ID**: `leistung`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LeistungDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LeistungDocumentData>,
    "leistung",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | InfoGridSlice
  | RichTextSlice
  | GamesSlice
  | CustomerLogosSlice
  | TextWithImageSlice
  | EventsSlice
  | LeistungenSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Menu Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Navigation Item field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].navigation_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_item: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Buttons field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.buttons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "default" | "secondary"
    >
  >;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | EventDocument
  | EventsOverviewPageDocument
  | GameDocument
  | HomepageDocument
  | LeistungDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Email field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Telefon field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.telefon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telefon: prismic.KeyTextField;

  /**
   * Addresse field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.addresse
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  addresse: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *Sponsors → Default → Primary → logos*
 */
export interface CustomerLogosSliceDefaultPrimaryLogosItem {
  /**
   * Image field in *Sponsors → Default → Primary → logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.logos[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *Sponsors → Default → Primary → logos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.logos[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Sponsors → Default → Primary*
 */
export interface CustomerLogosSliceDefaultPrimary {
  /**
   * Title field in *Sponsors → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * logos field in *Sponsors → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<
    Simplify<CustomerLogosSliceDefaultPrimaryLogosItem>
  >;
}

/**
 * Default variation for Sponsors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomerLogosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Sponsors*
 */
type CustomerLogosSliceVariation = CustomerLogosSliceDefault;

/**
 * Sponsors Shared Slice
 *
 * - **API ID**: `customer_logos`
 * - **Description**: CustomerLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSlice = prismic.SharedSlice<
  "customer_logos",
  CustomerLogosSliceVariation
>;

/**
 * Primary content in *Events → Default → Primary*
 */
export interface EventsSliceDefaultPrimary {
  /**
   * Title field in *Events → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Events → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Background Color field in *Events → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"Black" | "Grey">;
}

/**
 * Default variation for Events Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Events*
 */
type EventsSliceVariation = EventsSliceDefault;

/**
 * Events Shared Slice
 *
 * - **API ID**: `events`
 * - **Description**: Events
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSlice = prismic.SharedSlice<"events", EventsSliceVariation>;

/**
 * Primary content in *Games → Default → Primary*
 */
export interface GamesSliceDefaultPrimary {
  /**
   * Title field in *Games → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: games.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Games → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: games.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Background Color field in *Games → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: games.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"Black" | "Grey">;
}

/**
 * Default variation for Games Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GamesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GamesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Games*
 */
type GamesSliceVariation = GamesSliceDefault;

/**
 * Games Shared Slice
 *
 * - **API ID**: `games`
 * - **Description**: Games
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GamesSlice = prismic.SharedSlice<"games", GamesSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Links field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *InfoGrid → 3 Columns → Primary → Elements*
 */
export interface InfoGridSliceDefaultPrimaryElementsItem {
  /**
   * Title field in *InfoGrid → 3 Columns → Primary → Elements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.default.primary.elements[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *InfoGrid → 3 Columns → Primary → Elements*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.default.primary.elements[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Icon field in *InfoGrid → 3 Columns → Primary → Elements*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.default.primary.elements[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Full Width field in *InfoGrid → 3 Columns → Primary → Elements*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: info_grid.default.primary.elements[].full_width
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_width: prismic.BooleanField;
}

/**
 * Item in *InfoGrid → 2 Columns → Primary → Elements*
 */
export interface InfoGridSlice2ColumnsPrimaryElementsItem {
  /**
   * Title field in *InfoGrid → 2 Columns → Primary → Elements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.2Columns.primary.elements[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *InfoGrid → 2 Columns → Primary → Elements*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.2Columns.primary.elements[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Icon field in *InfoGrid → 2 Columns → Primary → Elements*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.2Columns.primary.elements[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Full Width field in *InfoGrid → 2 Columns → Primary → Elements*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: info_grid.2Columns.primary.elements[].full_width
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_width: prismic.BooleanField;
}

/**
 * Item in *InfoGrid → 4 Columns → Primary → Elements*
 */
export interface InfoGridSlice4ColumnsPrimaryElementsItem {
  /**
   * Title field in *InfoGrid → 4 Columns → Primary → Elements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.4Columns.primary.elements[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *InfoGrid → 4 Columns → Primary → Elements*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.4Columns.primary.elements[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Icon field in *InfoGrid → 4 Columns → Primary → Elements*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.4Columns.primary.elements[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Full Width field in *InfoGrid → 4 Columns → Primary → Elements*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: info_grid.4Columns.primary.elements[].full_width
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_width: prismic.BooleanField;
}

/**
 * Primary content in *InfoGrid → 3 Columns → Primary*
 */
export interface InfoGridSliceDefaultPrimary {
  /**
   * Title field in *InfoGrid → 3 Columns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Elements field in *InfoGrid → 3 Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.default.primary.elements[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  elements: prismic.GroupField<
    Simplify<InfoGridSliceDefaultPrimaryElementsItem>
  >;

  /**
   * Background Color field in *InfoGrid → 3 Columns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"Black" | "Grey">;
}

/**
 * 3 Columns variation for InfoGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *InfoGrid → 2 Columns → Primary*
 */
export interface InfoGridSlice2ColumnsPrimary {
  /**
   * Title field in *InfoGrid → 2 Columns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.2Columns.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Elements field in *InfoGrid → 2 Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.2Columns.primary.elements[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  elements: prismic.GroupField<
    Simplify<InfoGridSlice2ColumnsPrimaryElementsItem>
  >;

  /**
   * Background Color field in *InfoGrid → 2 Columns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.2Columns.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"Black" | "Grey">;
}

/**
 * 2 Columns variation for InfoGrid Slice
 *
 * - **API ID**: `2Columns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoGridSlice2Columns = prismic.SharedSliceVariation<
  "2Columns",
  Simplify<InfoGridSlice2ColumnsPrimary>,
  never
>;

/**
 * Primary content in *InfoGrid → 4 Columns → Primary*
 */
export interface InfoGridSlice4ColumnsPrimary {
  /**
   * Title field in *InfoGrid → 4 Columns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.4Columns.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Elements field in *InfoGrid → 4 Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.4Columns.primary.elements[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  elements: prismic.GroupField<
    Simplify<InfoGridSlice4ColumnsPrimaryElementsItem>
  >;

  /**
   * Background Color field in *InfoGrid → 4 Columns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: info_grid.4Columns.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"Black" | "Grey">;
}

/**
 * 4 Columns variation for InfoGrid Slice
 *
 * - **API ID**: `4Columns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoGridSlice4Columns = prismic.SharedSliceVariation<
  "4Columns",
  Simplify<InfoGridSlice4ColumnsPrimary>,
  never
>;

/**
 * Slice variation for *InfoGrid*
 */
type InfoGridSliceVariation =
  | InfoGridSliceDefault
  | InfoGridSlice2Columns
  | InfoGridSlice4Columns;

/**
 * InfoGrid Shared Slice
 *
 * - **API ID**: `info_grid`
 * - **Description**: InfoGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoGridSlice = prismic.SharedSlice<
  "info_grid",
  InfoGridSliceVariation
>;

/**
 * Primary content in *Leistungen → Default → Primary*
 */
export interface LeistungenSliceDefaultPrimary {
  /**
   * Title field in *Leistungen → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leistungen.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Leistungen → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leistungen.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Background Color field in *Leistungen → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: leistungen.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"Black" | "Grey">;
}

/**
 * Default variation for Leistungen Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeistungenSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LeistungenSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Leistungen*
 */
type LeistungenSliceVariation = LeistungenSliceDefault;

/**
 * Leistungen Shared Slice
 *
 * - **API ID**: `leistungen`
 * - **Description**: Leistungen
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeistungenSlice = prismic.SharedSlice<
  "leistungen",
  LeistungenSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *TeamRoaster → Default → Primary → Players*
 */
export interface TeamSliceDefaultPrimaryPlayersItem {
  /**
   * Portrait field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Gamer Tag field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].gamer_tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gamer_tag: prismic.KeyTextField;

  /**
   * Studienfach field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].studienfach
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  studienfach: prismic.KeyTextField;

  /**
   * Info 1 Label field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].info_1_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_1_label: prismic.KeyTextField;

  /**
   * Info 1 field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].info_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_1: prismic.KeyTextField;

  /**
   * Info 2 Label field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].info_2_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_2_label: prismic.KeyTextField;

  /**
   * Info 2 field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].info_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_2: prismic.KeyTextField;

  /**
   * Zitat field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].zitat
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  zitat: prismic.KeyTextField;

  /**
   * Role field in *TeamRoaster → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;
}

/**
 * Primary content in *TeamRoaster → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Players field in *TeamRoaster → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.players[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  players: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryPlayersItem>>;
}

/**
 * Default variation for TeamRoaster Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamRoaster*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * TeamRoaster Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Primary content in *TeamInfo → Default → Primary*
 */
export interface TeamInfoSliceDefaultPrimary {
  /**
   * Title field in *TeamInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_info.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *TeamInfo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_info.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Team Foto field in *TeamInfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_info.default.primary.team_foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  team_foto: prismic.ImageField<never>;
}

/**
 * Default variation for TeamInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamInfo*
 */
type TeamInfoSliceVariation = TeamInfoSliceDefault;

/**
 * TeamInfo Shared Slice
 *
 * - **API ID**: `team_info`
 * - **Description**: TeamInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamInfoSlice = prismic.SharedSlice<
  "team_info",
  TeamInfoSliceVariation
>;

/**
 * Primary content in *TextWithImage → ImageRight → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *TextWithImage → ImageRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → ImageRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Aspect Ratio field in *TextWithImage → ImageRight → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.image_aspect_ratio
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_aspect_ratio: prismic.SelectField<"1:1" | "16:9">;

  /**
   * Links field in *TextWithImage → ImageRight → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "default" | "secondary" | "ghost" | "outline" | "destructive" | "link"
    >
  >;

  /**
   * Inverse Colors field in *TextWithImage → ImageRight → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_with_image.default.primary.inverse_colors
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  inverse_colors: prismic.BooleanField;
}

/**
 * ImageRight variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextWithImage → ImageLeft → Primary*
 */
export interface TextWithImageSliceImageLeftPrimary {
  /**
   * Text field in *TextWithImage → ImageLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.imageLeft.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → ImageLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Aspect Ratio field in *TextWithImage → ImageLeft → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.imageLeft.primary.image_aspect_ratio
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_aspect_ratio: prismic.SelectField<"1:1" | "16:9">;

  /**
   * Links field in *TextWithImage → ImageLeft → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.imageLeft.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "default" | "secondary" | "ghost" | "outline" | "destructive" | "link"
    >
  >;

  /**
   * Inverse Colors field in *TextWithImage → ImageLeft → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_with_image.imageLeft.primary.inverse_colors
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  inverse_colors: prismic.BooleanField;
}

/**
 * ImageLeft variation for TextWithImage Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<TextWithImageSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation =
  | TextWithImageSliceDefault
  | TextWithImageSliceImageLeft;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EventDocument,
      EventDocumentData,
      EventDocumentDataSlicesSlice,
      EventsOverviewPageDocument,
      EventsOverviewPageDocumentData,
      EventsOverviewPageDocumentDataSlicesSlice,
      GameDocument,
      GameDocumentData,
      GameDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LeistungDocument,
      LeistungDocumentData,
      LeistungDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      CustomerLogosSlice,
      CustomerLogosSliceDefaultPrimaryLogosItem,
      CustomerLogosSliceDefaultPrimary,
      CustomerLogosSliceVariation,
      CustomerLogosSliceDefault,
      EventsSlice,
      EventsSliceDefaultPrimary,
      EventsSliceVariation,
      EventsSliceDefault,
      GamesSlice,
      GamesSliceDefaultPrimary,
      GamesSliceVariation,
      GamesSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      InfoGridSlice,
      InfoGridSliceDefaultPrimaryElementsItem,
      InfoGridSliceDefaultPrimary,
      InfoGridSlice2ColumnsPrimaryElementsItem,
      InfoGridSlice2ColumnsPrimary,
      InfoGridSlice4ColumnsPrimaryElementsItem,
      InfoGridSlice4ColumnsPrimary,
      InfoGridSliceVariation,
      InfoGridSliceDefault,
      InfoGridSlice2Columns,
      InfoGridSlice4Columns,
      LeistungenSlice,
      LeistungenSliceDefaultPrimary,
      LeistungenSliceVariation,
      LeistungenSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryPlayersItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TeamInfoSlice,
      TeamInfoSliceDefaultPrimary,
      TeamInfoSliceVariation,
      TeamInfoSliceDefault,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceImageLeftPrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TextWithImageSliceImageLeft,
    };
  }
}
