// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  customer_logos: dynamic(() => import("./Sponsors")),
  events: dynamic(() => import("./Events")),
  leistungen: dynamic(() => import("./Leistungen")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
